curso/urls.py
from django.urls import path
from curso import views

app_name = 'curso'
urlpatterns = [
    path('', views.courses, name='index'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('contact/', views.contact, name='contact'),
    path('enrollment/<slug:slug>', views.enrollment, name='enrollment'),

]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import *

urlpatterns = [
    path('enquetes/', include('enquete.urls')),
    path('user/', include('user.urls')),
    path('', include('curso.urls')),
    path('admin/', admin.site.urls),
]

enquete/urls.py
from django.urls import path
from enquete import views

# Namespace da aplicação
app_name = 'enquete'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('allresults/', views.allresults, name='allresults'),
    # Substituindo views.<name_template> --> views.NameView.as_view()
]

user/urls.py
from django.urls import path, base
from django.urls.conf import include
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='curso:index'), name='logout'),
    path('panel/', views.panel, name='panel'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('edit_password/', views.edit_password, name='edit_password'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='user/reset.html',
        email_template_name='user/reset_email.html',
        success_url=base.reverse_lazy('user:password_reset_done')), name='password_reset'),
    path('reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='user/reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/reset_confirm.html', 
        success_url=base.reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/reset_complete.html'), name='password_reset_complete'),
]

enquete/models.py
import datetime
from django.utils import timezone
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

enquete/views.py
from django.forms import ModelForm
from django.http.response import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
#from django.http import HttpResponse
#from django.template import context, loader
from django.urls import reverse

from .models import Choice, Question

# Creating views here.
# ex: /enquete/ 
''' 
    def index(request): 
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])
    
    # Retorno de template e contexto direto no HttpResponse
    template = loader.get_template('enquete/index.html')
    context = {'latest_question_list': latest_question_list}   
    return HttpResponse(template.render(context, request))
'''
    
def index(request): 
    latest_question_list = Question.objects.order_by('-pub_date')[:5]

    # Atalho render para retornar o template e contexto
    context = {'latest_question_list': latest_question_list}
    return render(request, 'enquete/index.html', context)

# ex: /enquete/5/
'''
    def detail(request, question_id):
    # return HttpResponse('You\'re looking at question %s.' % question_id)
    # Resolvendo erro 404 do objeto para o retorno
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404('Question does not exist!')
    return render(request, 'enquete/detail.html', {'question': question})
'''

def detail(request, question_id):
    # Atalho para retornar diretamente o objeto se não houver erro
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'enquete/detail.html', {'question': question})

# ex: /enquete/5/results
'''
    def results(request, question_id):
    # Retorno do objeto direto no response
    response = ('You\'re looking at the results of question %s.')
    return HttpResponse(response % question_id)
'''

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'enquete/results.html', {'question': question})

def allresults(request):
    latest_question_list = Question.objects.order_by('-pub_date')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'enquete/results.html', context)

# ex: //5/vote
def vote(request, question_id):
    # return HttpResponse('You\'re voting on question %s.' % question_id)'''

    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Mostra novamente o formulário de voto
        return render(request, 'enquete/detail.html', {
            'question': question,
            'error_message': "Você não marcou uma escolha válida!",
        })
    else:
        selected_choice.votes +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('enquete:results', args=(question_id,)))

enquete/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DjangoSite - Enquetes</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css" integrity="sha384-Uu6IeWbM+gzNVXJcM9XV3SohHtmWE+3VGi496jvgX1jyvDTXfdK+rfZc8C1Aehk5" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="body" style="width:1200px; margin-left: auto; margin-right: auto;">
        <div class="pure-menu pure-menu-horizontal">
            <a href="{% url 'enquete:index' %}" class="pure-menu-heading pure-menu-link">ENQUETES - DjangoSite</a>
            <ul class="pure-menu-list">
                <li class="pure-menu-item">
                    <a href="{% url 'enquete:index' %}" class="pure-menu-link">Enquetes</a>
                </li>
                <li class="pure-menu-item">
                    <a href="{% url 'enquete:allresults' %}" class="pure-menu-link">Resultados</a>
                </li>
                <li class="pure-menu-item">
                    <a href="{% url 'enquete:contact' %}" class="pure-menu-link">Contato</a>
                </li>
            </ul>
        </div>
        <div class="">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</body>
</html>

enquete/templates/contact.html
{% extends 'base.html' %} 
{% block content %} 
<form class="pure-form pure-form-stacked" action=".">
    <fieldset>
        <legend><h3>Página de Contato:</h3></legend>
    </fieldset>
    {% csrf_token %} 
    {{ contato.as_p }} 
    <input class="pure-button" type="submit" name="Enviar">
</form>
{% endblock %} 

enquete/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% if latest_question_list %} 
    <ul class="">
        {% for question in latest_question_list %} 
        <!-- Inserindo URL codificada do template diretamente
        <li><a href="/enquete/{{ question.id }}">{{ question.question_text }}</a></li>-->

        <!-- Removendo URLs codificadas pela tag %url% namespace:template-->
        <li>
            <a class="" href="{% url 'enquete:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %} 
    </ul>
{% else %} 
    <p>Não há enquetes disponíveis.</p>
{% endif %} 
{% endblock %}

enquete/templates/results.html
{% extends 'base.html' %}
{% block content %}
{% if latest_question_list %}
    <ul>
        {% for l in latest_question_list %} 
            <li>
                <h3>{{ l.question_text }}</h3>
                <ul>
                    {% for q in l.choice_set.all %} 
                    <li>{{ q.choice_text }} || {{ q.votes }} voto{{ q.votes|pluralize }}</li>
                    {% endfor %} 
                </ul>
            </li>    
        {% endfor %} 
    </ul>
{% else %} 
    <h3>{{ question.question_text }}</h3>

    <ul>
        {% for choice in question.choice_set.all %} 
        <li>{{ choice.choice_text }} || {{ choice.votes }} voto{{ choice.votes|pluralize }}</li>
        {% endfor %} 
    </ul>

    <a class="pure-button" href="{% url 'enquete:detail' question.id %}">Votar novamente?</a>
    <a class="pure-button" href="{% url 'enquete:index' %}">Voltar ao início!</a>
{% endif %} 
{% endblock %} 