curso/urls.py
from django.urls import path
from curso import views

app_name = 'curso'
urlpatterns = [
    path('', views.courses, name='index'),
    path('detail/<slug:slug>', views.detail, name='detail'),
    path('contact/', views.contact, name='contact'),
    path('enrollment/<slug:slug>', views.enrollment, name='enrollment'),

]

djangosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import *

urlpatterns = [
    path('enquetes/', include('enquete.urls')),
    path('user/', include('user.urls')),
    path('', include('curso.urls')),
    path('admin/', admin.site.urls),
]

enquete/urls.py
from django.urls import path
from enquete import views

# Namespace da aplicação
app_name = 'enquete'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('allresults/', views.allresults, name='allresults'),
    # Substituindo views.<name_template> --> views.NameView.as_view()
]

user/urls.py
from django.urls import path, base
from django.urls.conf import include
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='curso:index'), name='logout'),
    path('panel/', views.panel, name='panel'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('edit_password/', views.edit_password, name='edit_password'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='user/reset.html',
        email_template_name='user/reset_email.html',
        success_url=base.reverse_lazy('user:password_reset_done')), name='password_reset'),
    path('reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='user/reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/reset_confirm.html', 
        success_url=base.reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/reset_complete.html'), name='password_reset_complete'),
]

djangosite/templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a responsive product landing page.">
    <title>DjangoSite</title>
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/pure-min.css">
    <link rel="stylesheet" href="https://unpkg.com/purecss@2.0.6/build/grids-responsive-min.css">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <link rel="stylesheet" href="{% static 'styles.css'%}">
</head>
<body>

<div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a href="{% url 'curso:index' %}" class="pure-menu-heading pure-menu-link">DjangoSite</a>
        <ul class="pure-menu-list">
            <li class="pure-menu-item">
                <a href="{% url 'curso:index' %}" class="pure-menu-link">Cursos</a>
            </li>
            <li class="pure-menu-item">
                <a href="{% url 'enquete:index' %}" class="pure-menu-link">Enquetes</a>
            </li>
            <li class="pure-menu-item">
                <a href="{% url 'enquete:allresults' %}" class="pure-menu-link">Resultados</a>
            </li>
            <li class="pure-menu-item">
                <a href="{% url 'curso:contact' %}" class="pure-menu-link">Contato</a>
            </li>
            {% if user.is_authenticated %} 
            <li class="pure-menu-item">
                <a href="{% url 'user:panel' %}" class="pure-menu-link">Painel</a>
            </li>
            <li class="pure-menu-item">
                <a href="{% url 'user:logout' %}" class="pure-menu-link">Sair</a>
            </li>
            {% else %} 
            <li class="pure-menu-item">
                <a href="{% url 'user:login' %}" class="pure-menu-link">Entrar</a>
            </li>
            {% endif %} 
        </ul>
    </div>
</div>

<div class="splash-container">
    <div class="splash">
        <h1 class="splash-head">DjangoSite</h1>
        <p class="splash-subhead">
            Plataforma de Cursos Online
        </p>
        <p>
            <a href="{% url 'curso:index' %}" class="pure-button pure-button-primary">Get Started</a>
        </p>
    </div>
</div>

<div class="content-wrapper">
    <div class="content">
    {% block content %} 
    {% endblock %} 

    </div>
    <div class="content">
        <h2 class="content-head is-center"></h2>

        <div class="pure-g">
            <div class="l-box pure-u-1 pure-u-md-1-2 pure-u-lg-1-4">
                <h3 class="content-subhead">
                    <i class="fa"></i>
                </h3>
                <p>

                </p>
            </div>
    </div>

    <div class="ribbon l-box-lrg pure-g">
        <div class="l-box-lrg is-center pure-u-1 pure-u-md-1-2 pure-u-lg-2-5">
            <!--<img width="300" alt="File Icons" class="pure-img-responsive" src="">-->
        </div>
        <div class="pure-u-1 pure-u-md-1-2 pure-u-lg-3-5">

            <h2 class="content-head content-head-ribbon">Laboris nisi ut aliquip.</h2>

            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                consequat. Duis aute irure dolor.
            </p>
        </div>
    </div>


</div>
<div class="footer l-box is-center">
    Desenvolvido por Alésio Torres em processo do curso Django para Web com prof. Gileno Alves.
</div>

</body>
</html>