djangosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views import *

urlpatterns = [
    path('enquetes/', include('enquete.urls')),
    path('user/', include('user.urls')),
    path('', include('curso.urls')),
    path('admin/', admin.site.urls),
]

user/urls.py
from django.urls import path, base
from django.urls.conf import include
from user import views
from django.contrib.auth import views as auth_views

app_name = 'user'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('register/', views.register, name='register'),
    path('logout/', auth_views.LogoutView.as_view(next_page='curso:index'), name='logout'),
    path('panel/', views.panel, name='panel'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('edit_password/', views.edit_password, name='edit_password'),
    path('reset/', auth_views.PasswordResetView.as_view(
        template_name='user/reset.html',
        email_template_name='user/reset_email.html',
        success_url=base.reverse_lazy('user:password_reset_done')), name='password_reset'),
    path('reset/done', auth_views.PasswordResetDoneView.as_view(
        template_name='user/reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='user/reset_confirm.html', 
        success_url=base.reverse_lazy('user:password_reset_complete')), name='password_reset_confirm'),
    path('reset_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='user/reset_complete.html'), name='password_reset_complete'),
]

user/models.py
from io import RawIOBase
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.deletion import CASCADE

# Model customizado para recuperação de senha
'''
class PasswordReset(models.Model):
    user = models.ForeignKey(User, on_delete=CASCADE, verbose_name='Usuário')
    key = models.CharField('Chave', max_length=100, unique=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)

    def __str__(self) -> str:
        return super().__str__()'''

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import fields
from .models import User

# Formulário para cadastro do usuário
class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail')
    first_name = forms.CharField(label='Nome')
    last_name = forms.CharField(label='Sobrenome')
    #birthdate = forms.DateField(label='Data de nascimento')

    # Função para validar email já cadastrado
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('E-mail já cadastrado, favor preencher um novo email.')
        return email

    # Função herdada de UserCreationForm para cadastros de novos campos do user
    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.firstname = self.cleaned_data['firstname']
        user.lastname = self.cleaned_data['lastname']
        if commit:
            user.save()
        return user

# Formulário para alteração do cadastro de usuário
class EditUserForm(forms.ModelForm):
    # Função para validar email já cadastrado
    def clean_email(self):
        email = self.cleaned_data['email']
        query_set = User.objects.filter(email=email).exclude(pk=self.instance.pk)
        if query_set.exists():
            raise forms.ValidationError('E-mail já cadastrado, favor preencher um novo email.')
        return email
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

user/views.py
from django import contrib
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm, UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render, get_object_or_404
from django.conf import settings

from user.forms import RegisterForm, EditUserForm
from curso.models import Enrollment

# View para cadastro de usuários no django
def register(request):
    template_name = 'user/register.html' 
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save()

        # Messagem de sucesso para view register
        messages.success(request, 'Parabéns, cadastro concluído com sucesso.')

        # Login automático após cadastro
        user = authenticate(
            username = user.username,
            password = form.cleaned_data['password1'],
        )
        login(request, user)
        # Retorno para index após cadastro
        return redirect('user:panel')
        
        # Retorno para tela de URL após cadastro
        # return redirect(settings.LOGIN_URL)
    return render(request, template_name, {'form': form})

# View para painel do usuário com requisição de login
# Redireciona ao login automaticamente caso não esteja logado
@login_required    
def panel(request):
    template_name = 'user/panel.html'
    context = {}

    # Contexto para carregar Enrollments do usuário numa view específica
    # context['enrollments'] = Enrollment.objects.filter(user=request.user)
    return render(request, template_name, context)

# View para edição dos campos do usuário
@login_required
def edit_user(request):
    template_name = 'user/edit_user.html'
    form = EditUserForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        form = EditUserForm(instance=request.user)
        messages.success(request, 'Cadastro atualizado.')
    return render(request, template_name, {'form': form})

# View para alterar senha do usuário
@login_required
def edit_password(request):
    template_name = 'user/edit_password.html'
    form = PasswordChangeForm(data=request.POST, user=request.user)
    if form.is_valid():
        form.save()
        messages.success(request, 'Senha atualizada.')
    return render(request, template_name, {'form': form})

user/templates/user/dashboard.html
{% extends 'user/base.html' %} 
{% block content %} 
<div class="pure-g content-ribbon">
    {% if messages %}
    <aside class="pure-u-1">
        {% for message in messages %}
        <p>{{ message }}</p>
        {% endfor %}
    </aside>
    {% endif %}
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %} 
            <a href="{% url 'user:dashboard' %}">Meu Painel</a>
            {% endblock %} 
        </ul>
    </div>
    <div class="pure-u-1-3">
        <div class="pure-meu pure-menu-open" >
            <a class="pure-menu-heading">Meus Cursos</a>
            <ul>
                <li><a href="#">Curso 1</a></li>
                <li><a href="#">Curso 1</a></li>
            </ul>
        </div>
        <div class="pure-meu pure-menu-open" >
        <a class="pure-menu-heading">Minha Conta</a></li>
            <ul>
                <li><a href="{% url 'user:edit_user' %}">Editar Conta</a></li>
                <li><a href="{% url 'user:edit_password' %}">Alterar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="inner">
            {% block dashboard_content %} 
            <p><strong>Usuário: </strong>{{ user }}</p>
            <p><strong>Email: </strong>{{ user.email }}</p>
            {% endblock %} 
        </div>
    </div>
</div>
{% endblock %} 

user/templates/user/edit_password.html
{% extends 'user/panel.html' %} 

{% block breadcrumb %} 
    {{ block.super }}
    / <a href="{% url 'user:edit_password' %}">Alterar Senha</a></li>
{% endblock %} 

{% block panel_content %} 
<div class="pure-u-1-2">
    <form class="pure-form pure-form-stacked" action="." method="POST">
        {% csrf_token %} 
        <fieldset>
            <legend>Alterar Senha</legend>
            {{ form.non_field_errors }}
            {% for field in form %} 
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %} 
        </fieldset>
        <div class="pure-controls">
            <button class="pure-button pure-button-primary" type="submit">Salvar</button>
        </div>
    </form>
</div>
{% endblock %} 

user/templates/user/edit_user.html
{% extends 'user/panel.html' %} 

{% block breadcrumb %} 
    {{ block.super }}
    / <a href="{% url 'user:edit_user' %}">Editar Conta</a></li>
{% endblock %} 

{% block panel_content %} 
<div class="pure-u-1-2">
    <form class="pure-form pure-form-stacked" action="." method="POST">
        {% csrf_token %} 
        <fieldset>
            <legend>Editar Conta</legend>
            {{ form.non_field_errors }}
            {% for field in form %} 
            <div class="pure-control-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %} 
        </fieldset>
        <div class="pure-controls">
            <button class="pure-button pure-button-primary" type="submit">Salvar</button>
        </div>
    </form>
</div>
{% endblock %} 

user/templates/user/login.html
{% extends 'base.html' %} 
{% block content %} 
<div class="pure-g">
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5 is-center">
        <form class="pure-form pure-form-stacked" action="." method="POST">
            <fieldset>
                <legend>Login</legend>
                {% csrf_token %} 
                {{ form.non_field_errors }} 
                {% for field in form %} 
                <div class="pure-control-group">
                    {{ field.label_tag }} 
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %} 
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary" >Entrar</button>
                    <a class="pure-button" href="{% url 'user:register' %}">Cadastrar</a>
                </div>
            </fieldset>
        </form>
        <p>Esqueceu a senha? <a href="{% url 'user:password_reset' %}">Nova senha</a></p>
    </div>
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5"></div>
</div>
{% endblock %}

user/templates/user/panel.html
{% extends 'base.html' %} 
{% load courses_tags %}
{% block content %} 
{% if messages %}
<aside class="pure-u-1">
    {% for message in messages %}
    <p>{{ message }}</p>
    {% endfor %}
</aside>
{% endif %}
<div class="pure-g content-ribbon">
    <div class="pure-u-1">
        <ul class="breadcrumb">
            {% block breadcrumb %} 
            <a href="{% url 'user:panel' %}">Meu Painel</a>
            {% endblock %} 
        </ul>
    </div>
    <div class="pure-u-1-5">
        <div class="pure-menu pure-menu-open" >
            <a class="pure-menu-heading">Meus Cursos</a>
            {% my_courses user %}
        </div>
        <div class="pure-menu pure-menu-open" >
        <a class="pure-menu-heading">Minha Conta</a></li>
            <ul>
                <li><a href="{% url 'user:edit_user' %}">Editar Conta</a></li>
                <li><a href="{% url 'user:edit_password' %}">Alterar Senha</a></li>
            </ul>
        </div>
    </div>
    <div class="pure-u-2-5">
        <div class="inner">
            {% block panel_content %} 
            <p><strong>Usuário: </strong>{{ user }}</p>
            <p><strong>Email: </strong>{{ user.email }}</p>
            {% endblock %} 
        </div>
    </div>
</div>
{% endblock %} 

user/templates/user/register.html
{% extends 'base.html' %} 
{% block content %} 
<div class="pure-g" >
    <div class="pure-u-1-3"></div>
    <div class="pure-u-1-3">
        <form class="pure-form pure-form-stacked" action="." method="POST">
            <fieldset>
                <legend>Formlário de Cadastro</legend>
                {% csrf_token %} 
                {{ form.non_field_errors }} 
                {% for field in form %} 
                <div class="pure-control-group">
                    {{ field.label_tag }} 
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %} 
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary" >Cadastrar</button>
                </div>
            </fieldset>
        </form>
        <p>Esqueceu a senha? <a href="{% url 'user:password_reset' %}">Nova senha</a></p>
        <p>Já é cadastrado? <a href="{% url 'user:login' %}">Efetue login</a></p>

    </div>
    <div class="pure-u-1-3"></div>
</div>
{% endblock %}

user/templates/user/reset.html
{% extends 'base.html' %} 
{% block content %} 
<div class="pure-g" >
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5 is-center">
        <form class="pure-form pure-form-stacked" action="." method="POST">
            <fieldset>
                <legend>Restaurar Senha</legend>
                {% csrf_token %} 
                {{ form.non_field_errors }} 
                {% for field in form %} 
                <div class="pure-control-group">
                    {{ field.label_tag }} 
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %} 
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary" >Enviar</button>
                </div>
            </fieldset>
        </form>
        <p>Não é cadastrado? <a href="{% url 'user:register' %}">Cadastre-se</a></p>
        <p>Já possui cadastro? <a href="{% url 'user:login' %}">Efetue Login</a></p>
    </div>
    <div class="pure-u-1-5"></div>
    <div class="pure-u-1-5"></div>
</div>
{% endblock %}

user/templates/user/reset_complete.html
{% extends 'base.html' %} 
{% block content %} 
<form class="pure-form pure-form-stacked" action="" method="POST">
    <fieldset>
        <legend>Senha Restaurada com Sucesso!</legend>
    </fieldset>
    <div class="pure-control-group">
        <p>Senha restaurada com sucesso.</p>
    </div>
    <div class="pure-controls">
        <p><a class="pure-button pure-button-primary" href="{% url 'user:login' %}">Efetuar Login</a></p>
    </div>
</form>
{% endblock %}

user/templates/user/reset_confirm.html
{% extends 'base.html' %} 
{% block content %} 
<div class="pure-g" ></div>
<div class="pure-u-1-3"></div>
<div class="pure-u-1-3 is-center">
    <form class="pure-form pure-form-stacked" action="" method="POST">
        <fieldset>
            <legend>Confirmação de Senha</legend>
            {% csrf_token %} 
            {{ form.non_field_errors }} 
            {% for field in form %} 
            <div class="pure-control-group">
                {{ field.label_tag }} 
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %} 
            <div class="pure-controls">
                <button type="submit" class="pure-button pure-button-primary">Enviar</button>
            </div>
        </fieldset>
    </form>
    <p>Não é cadastrado? <a href="{% url 'user:register' %}">Cadastre-se</a></p>
    <p>Já possui cadastro? <a href="{% url 'user:login' %}">Efetue Login</a></p>
</div>
<div class="pure-u-1-3"></div>
{% endblock %}

user/templates/user/reset_done.html
{% extends 'base.html' %} 
{% block content %} 
<div class="pure-g">
    <div class="pure-u-1-3"></div>
    <div class="pure-u-1-3 is-center">
        <h3>Restauração de Senha</h3>
        <p>Enviamos um email para você com o link para restauração de sua senha.</p>
        <p><a class="pure-button" href="">Voltar ao Início</a></p>
    </div>
    <div class="pure-u-1-3"></div>
</div>
{% endblock %}

user/templates/user/reset_email.html
Recebemos sua requisição para restauração de senha do E-mail: {{ email }} no site {{ site.name }}.

Siga o link a seguir para restaurar sua senha: {{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}